
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `stat_consume_banding_time_distribution`;
CREATE TABLE `stat_consume_banding_time_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL COMMENT '0-1点消费人数',
  `section_2` int(11) NOT NULL COMMENT '1-2点消费人数',
  `section_3` int(11) NOT NULL COMMENT '2-3点消费人数',
  `section_4` int(11) NOT NULL COMMENT '3-4点消费人数',
  `section_5` int(11) NOT NULL COMMENT '4-5点消费人数',
  `section_6` int(11) NOT NULL COMMENT '5-6点消费人数',
  `section_7` int(11) NOT NULL COMMENT '6-7点消费人数',
  `section_8` int(11) NOT NULL COMMENT '7-8点消费人数',
  `section_9` int(11) NOT NULL COMMENT '8-9点消费人数',
  `section_10` int(11) NOT NULL COMMENT '9-10点消费人数',
  `section_11` int(11) NOT NULL COMMENT '10-11点消费人数',
  `section_12` int(11) NOT NULL COMMENT '11-12点消费人数',
  `section_13` int(11) NOT NULL COMMENT '12-13点消费人数',
  `section_14` int(11) NOT NULL COMMENT '13-14点消费人数',
  `section_15` int(11) NOT NULL COMMENT '14-15点消费人数',
  `section_16` int(11) NOT NULL COMMENT '15-16点消费人数',
  `section_17` int(11) NOT NULL COMMENT '16-17点消费人数',
  `section_18` int(11) NOT NULL COMMENT '17-18点消费人数',
  `section_19` int(11) NOT NULL COMMENT '18-19点消费人数',
  `section_20` int(11) NOT NULL COMMENT '19-20点消费人数',
  `section_21` int(11) NOT NULL COMMENT '20-21点消费人数',
  `section_22` int(11) NOT NULL COMMENT '21-22点消费人数',
  `section_23` int(11) NOT NULL COMMENT '22-23点消费人数',
  `section_24` int(11) NOT NULL COMMENT '23-24点消费人数',
  `section_amount_1` bigint(20) NOT NULL COMMENT '0-1点消费金额',
  `section_amount_2` bigint(20) NOT NULL COMMENT '1-2点消费金额',
  `section_amount_3` bigint(20) NOT NULL COMMENT '2-3点消费金额',
  `section_amount_4` bigint(20) NOT NULL COMMENT '3-4点消费金额',
  `section_amount_5` bigint(20) NOT NULL COMMENT '4-5点消费金额',
  `section_amount_6` bigint(20) NOT NULL COMMENT '5-6点消费金额',
  `section_amount_7` bigint(20) NOT NULL COMMENT '6-7点消费金额',
  `section_amount_8` bigint(20) NOT NULL COMMENT '7-8点消费金额',
  `section_amount_9` bigint(20) NOT NULL COMMENT '8-9点消费金额',
  `section_amount_10` bigint(20) NOT NULL COMMENT '9-10点消费金额',
  `section_amount_11` bigint(20) NOT NULL COMMENT '10-11点消费金额',
  `section_amount_12` bigint(20) NOT NULL COMMENT '11-12点消费金额',
  `section_amount_13` bigint(20) NOT NULL COMMENT '12-13点消费金额',
  `section_amount_14` bigint(20) NOT NULL COMMENT '13-14点消费金额',
  `section_amount_15` bigint(20) NOT NULL COMMENT '14-15点消费金额',
  `section_amount_16` bigint(20) NOT NULL COMMENT '15-16点消费金额',
  `section_amount_17` bigint(20) NOT NULL COMMENT '16-17点消费金额',
  `section_amount_18` bigint(20) NOT NULL COMMENT '17-18点消费金额',
  `section_amount_19` bigint(20) NOT NULL COMMENT '18-19点消费金额',
  `section_amount_20` bigint(20) NOT NULL COMMENT '19-20点消费金额',
  `section_amount_21` bigint(20) NOT NULL COMMENT '20-21点消费金额',
  `section_amount_22` bigint(20) NOT NULL COMMENT '21-22点消费金额',
  `section_amount_23` bigint(20) NOT NULL COMMENT '22-23点消费金额',
  `section_amount_24` bigint(20) NOT NULL COMMENT '23-24点消费金额',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17272 DEFAULT CHARSET=utf8 COMMENT='绑定元宝消费时间点分布';

DROP TABLE IF EXISTS `stat_consume_banding_treasure`;
CREATE TABLE `stat_consume_banding_treasure` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `open_time` date NOT NULL COMMENT '开服时间',
  `open_days` int(11) NOT NULL COMMENT '开服天数',
  `is_open_day` int(11) NOT NULL COMMENT '当日是否是开服日(是否是今日开服)',
  `dau` int(11) NOT NULL COMMENT '活跃人数(登陆人数)',
  `mau` int(11) NOT NULL COMMENT '月活跃用户数',
  `dru` int(11) NOT NULL COMMENT '日新注册人数',
  `dru_gunfu` int(11) NOT NULL COMMENT '日新注册滚服用户数',
  `ou` int(11) NOT NULL COMMENT '老用户数',
  `mou` int(11) NOT NULL COMMENT '月老用户数',
  `mfu` int(11) DEFAULT NULL COMMENT '月首次消费绑定元宝人数（每天累加即为月消费人数）',
  `total` bigint(11) NOT NULL COMMENT '绑定元宝总量(剩余)',
  `produce` bigint(11) NOT NULL COMMENT '绑定元宝产出',
  `num` int(11) NOT NULL COMMENT '消费人数',
  `amount` bigint(20) NOT NULL COMMENT '消费金额',
  `times` int(11) NOT NULL COMMENT '消费次数',
  `nn_num` int(11) NOT NULL COMMENT '新新消费人数',
  `nn_amount` bigint(20) NOT NULL COMMENT '新新消费金额',
  `nn_times` int(11) NOT NULL COMMENT '新新消费次数',
  `on_num` int(11) NOT NULL COMMENT '老新消费人数',
  `on_amount` bigint(20) NOT NULL COMMENT '老新消费金额',
  `on_times` int(11) NOT NULL COMMENT '老新消费次数',
  `oo_num` int(11) NOT NULL COMMENT '老老消费人数',
  `oo_amount` bigint(20) NOT NULL COMMENT '老老消费金额',
  `first_num` int(11) NOT NULL COMMENT '首次消费人数',
  `first_amount` bigint(20) NOT NULL COMMENT '首次消费金额',
  `oo_times` int(11) NOT NULL COMMENT '老老消费次数',
  `log_year` int(11) NOT NULL COMMENT '统计年份',
  `log_month` int(11) NOT NULL COMMENT '统计月份',
  `log_day` int(11) NOT NULL COMMENT '统计日',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=24504 DEFAULT CHARSET=utf8 COMMENT='绑定元宝消耗';

DROP TABLE IF EXISTS `stat_consume_distribution`;
CREATE TABLE `stat_consume_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `resource_line` int(11) NOT NULL COMMENT '资源线',
  `active_panel` int(11) NOT NULL COMMENT '活动面板',
  `consume_treasure` bigint(11) NOT NULL COMMENT '元宝消耗',
  `consume_treasure_account` int(11) NOT NULL COMMENT '消耗元宝人数',
  `consume_treasure_times` int(11) NOT NULL COMMENT '消耗元宝次数',
  `consume_banding_treasure` int(11) NOT NULL COMMENT '绑定元宝消耗',
  `consume_banding_account` bigint(11) NOT NULL COMMENT '消耗绑定元宝人数',
  `consume_banding_times` int(11) NOT NULL COMMENT '绑定元宝消耗次数',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=205156 DEFAULT CHARSET=utf8 COMMENT='资源线、面板消费分布';

DROP TABLE IF EXISTS `stat_consume_time_distribution`;
CREATE TABLE `stat_consume_time_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL COMMENT '0-1点消费人数',
  `section_2` int(11) NOT NULL COMMENT '1-2点消费人数',
  `section_3` int(11) NOT NULL COMMENT '2-3点消费人数',
  `section_4` int(11) NOT NULL COMMENT '3-4点消费人数',
  `section_5` int(11) NOT NULL COMMENT '4-5点消费人数',
  `section_6` int(11) NOT NULL COMMENT '5-6点消费人数',
  `section_7` int(11) NOT NULL COMMENT '6-7点消费人数',
  `section_8` int(11) NOT NULL COMMENT '7-8点消费人数',
  `section_9` int(11) NOT NULL COMMENT '8-9点消费人数',
  `section_10` int(11) NOT NULL COMMENT '9-10点消费人数',
  `section_11` int(11) NOT NULL COMMENT '10-11点消费人数',
  `section_12` int(11) NOT NULL COMMENT '11-12点消费人数',
  `section_13` int(11) NOT NULL COMMENT '12-13点消费人数',
  `section_14` int(11) NOT NULL COMMENT '13-14点消费人数',
  `section_15` int(11) NOT NULL COMMENT '14-15点消费人数',
  `section_16` int(11) NOT NULL COMMENT '15-16点消费人数',
  `section_17` int(11) NOT NULL COMMENT '16-17点消费人数',
  `section_18` int(11) NOT NULL COMMENT '17-18点消费人数',
  `section_19` int(11) NOT NULL COMMENT '18-19点消费人数',
  `section_20` int(11) NOT NULL COMMENT '19-20点消费人数',
  `section_21` int(11) NOT NULL COMMENT '20-21点消费人数',
  `section_22` int(11) NOT NULL COMMENT '21-22点消费人数',
  `section_23` int(11) NOT NULL COMMENT '22-23点消费人数',
  `section_24` int(11) NOT NULL COMMENT '23-24点消费人数',
  `section_amount_1` bigint(20) NOT NULL COMMENT '0-1点消费金额',
  `section_amount_2` bigint(20) NOT NULL COMMENT '1-2点消费金额',
  `section_amount_3` bigint(20) NOT NULL COMMENT '2-3点消费金额',
  `section_amount_4` bigint(20) NOT NULL COMMENT '3-4点消费金额',
  `section_amount_5` bigint(20) NOT NULL COMMENT '4-5点消费金额',
  `section_amount_6` bigint(20) NOT NULL COMMENT '5-6点消费金额',
  `section_amount_7` bigint(20) NOT NULL COMMENT '6-7点消费金额',
  `section_amount_8` bigint(20) NOT NULL COMMENT '7-8点消费金额',
  `section_amount_9` bigint(20) NOT NULL COMMENT '8-9点消费金额',
  `section_amount_10` bigint(20) NOT NULL COMMENT '9-10点消费金额',
  `section_amount_11` bigint(20) NOT NULL COMMENT '10-11点消费金额',
  `section_amount_12` bigint(20) NOT NULL COMMENT '11-12点消费金额',
  `section_amount_13` bigint(20) NOT NULL COMMENT '12-13点消费金额',
  `section_amount_14` bigint(20) NOT NULL COMMENT '13-14点消费金额',
  `section_amount_15` bigint(20) NOT NULL COMMENT '14-15点消费金额',
  `section_amount_16` bigint(20) NOT NULL COMMENT '15-16点消费金额',
  `section_amount_17` bigint(20) NOT NULL COMMENT '16-17点消费金额',
  `section_amount_18` bigint(20) NOT NULL COMMENT '17-18点消费金额',
  `section_amount_19` bigint(20) NOT NULL COMMENT '18-19点消费金额',
  `section_amount_20` bigint(20) NOT NULL COMMENT '19-20点消费金额',
  `section_amount_21` bigint(20) NOT NULL COMMENT '20-21点消费金额',
  `section_amount_22` bigint(20) NOT NULL COMMENT '21-22点消费金额',
  `section_amount_23` bigint(20) NOT NULL COMMENT '22-23点消费金额',
  `section_amount_24` bigint(20) NOT NULL COMMENT '23-24点消费金额',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12777 DEFAULT CHARSET=utf8 COMMENT='绑定元宝消费时间点分布';

DROP TABLE IF EXISTS `stat_consume_treasure`;
CREATE TABLE `stat_consume_treasure` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `open_time` datetime NOT NULL COMMENT '开服时间',
  `open_days` int(11) NOT NULL COMMENT '开服天数',
  `is_open_day` int(11) NOT NULL COMMENT '当日是否是开服日(是否是今日开服)',
  `dau` int(11) NOT NULL COMMENT '活跃人数(登陆人数)',
  `dru` int(11) NOT NULL COMMENT '日新注册人数',
  `dru_gunfu` int(11) NOT NULL COMMENT '日新注册滚服用户数',
  `ou` int(11) NOT NULL COMMENT '老用户数',
  `mou` int(11) NOT NULL COMMENT '月老用户数',
  `mfu` int(11) DEFAULT NULL COMMENT '月首次消费元宝人数（每天累加即为月消费人数）',
  `num` int(11) NOT NULL COMMENT '消费人数',
  `amount` bigint(20) NOT NULL COMMENT '消费金额',
  `times` int(11) NOT NULL COMMENT '消费次数',
  `nn_num` int(11) NOT NULL COMMENT '新新消费人数',
  `nn_amount` bigint(20) NOT NULL COMMENT '新新消费金额',
  `nn_times` int(11) NOT NULL COMMENT '新新消费次数',
  `on_num` int(11) NOT NULL COMMENT '老新消费人数',
  `on_amount` bigint(20) NOT NULL,
  `on_times` int(11) NOT NULL COMMENT '老新消费次数',
  `oo_num` int(11) NOT NULL COMMENT '老老消费人数',
  `oo_amount` bigint(20) NOT NULL COMMENT '老老消费金额',
  `first_num` int(11) NOT NULL COMMENT '首次消费人数',
  `first_amount` bigint(20) NOT NULL COMMENT '首次消费金额',
  `oo_times` int(11) NOT NULL COMMENT '老老消费次数',
  `log_year` int(11) NOT NULL COMMENT '统计年份',
  `log_month` int(11) NOT NULL COMMENT '统计月份',
  `log_day` int(11) NOT NULL COMMENT '统计日',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=24519 DEFAULT CHARSET=utf8 COMMENT='元宝消耗';

DROP TABLE IF EXISTS `stat_goods_sales`;
CREATE TABLE `stat_goods_sales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `is_open_day` int(1) NOT NULL,
  `shop_type` int(11) NOT NULL COMMENT '商店类型',
  `item_id` varchar(255) NOT NULL COMMENT '物品ID',
  `item_name` varchar(255) NOT NULL COMMENT '物品名称',
  `item_num` int(11) NOT NULL COMMENT '物品数量',
  `ta` bigint(11) NOT NULL COMMENT 'Treasure Amount 消耗元宝金额',
  `ct` int(11) NOT NULL COMMENT 'consume times 元宝消耗次数',
  `tca` int(11) NOT NULL COMMENT 'Treasure Consume Account 元宝消费人数',
  `bta` bigint(11) NOT NULL COMMENT 'Banding Treasure Amount 绑定元宝消耗金额',
  `bct` int(11) NOT NULL COMMENT 'banding consume times 绑定元宝消费次数',
  `bca` int(11) NOT NULL COMMENT 'banding treasure consume account 绑定元宝消费人数',
  `log_month` int(11) NOT NULL,
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12156 DEFAULT CHARSET=utf8 COMMENT='道具销售统计';

DROP TABLE IF EXISTS `stat_integrated`;
CREATE TABLE `stat_integrated` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL COMMENT '服务器ID',
  `pv` int(11) NOT NULL COMMENT ' 创建页访问次数',
  `ru` int(11) NOT NULL COMMENT '总注册人数',
  `is_open_day` int(11) NOT NULL COMMENT '是否当日开服',
  `open_days` int(11) NOT NULL COMMENT '开服天数',
  `dru` int(11) NOT NULL COMMENT '日新注册人数',
  `dru_gunfu` int(11) NOT NULL COMMENT '日新注册滚服用户数',
  `dau` int(11) NOT NULL COMMENT '日活跃',
  `dau_duplicate` int(11) NOT NULL COMMENT '日活跃（不去重）',
  `mau` int(11) NOT NULL COMMENT '月活跃用户数（目前到哪一天就计算到哪一天）',
  `mou` int(11) NOT NULL COMMENT '月老用户数(目前是哪一天就计算到哪一天)',
  `mpu` int(11) NOT NULL COMMENT '月充值用户数(目前是哪一天就计算到哪一天)',
  `mopu` int(11) NOT NULL COMMENT '月老充值人数(目前是哪一天就计算到哪一天)',
  `rdau` int(11) NOT NULL COMMENT '滚服用户日活跃',
  `acu` int(11) NOT NULL COMMENT '平均在线人数',
  `gunfu_acu` int(11) NOT NULL COMMENT '滚服用户平均在线',
  `pcu` int(11) NOT NULL COMMENT '最高在线人数',
  `dt` int(11) NOT NULL COMMENT '用户平均在线时长',
  `gunfu_dt` int(11) NOT NULL COMMENT '滚服用户平均在线时长',
  `gunfu_income` decimal(18,2) NOT NULL COMMENT '滚服用户充值金额',
  `gunfu_pa` int(11) NOT NULL COMMENT '滚服用户充值人数',
  `income` decimal(11,2) NOT NULL COMMENT '日充值(RMB)',
  `pay_coin` bigint(11) NOT NULL COMMENT '日充值元宝数量',
  `consume_coin` bigint(11) NOT NULL COMMENT '日消耗元宝',
  `all_income` decimal(18,2) DEFAULT NULL,
  `all_pay_coin` bigint(11) NOT NULL COMMENT '总充值元宝',
  `all_consume_coin` bigint(11) NOT NULL COMMENT '总消耗元宝数',
  `all_surplus_coin` bigint(11) NOT NULL COMMENT '总剩余元宝数(剩余不等于充值减去消耗)',
  `nn_pa` int(11) NOT NULL COMMENT '新新充值人数',
  `nn_pay_times` int(11) NOT NULL COMMENT '新新充值次数',
  `nn_pay_value` decimal(11,2) NOT NULL COMMENT '新新充值金额(RMB)',
  `mnn_pa` int(11) NOT NULL COMMENT '月新新充值人数(目前是哪一天就计算到哪一天)',
  `on_pa` int(11) NOT NULL COMMENT '老新充值人数',
  `on_pay_times` int(11) NOT NULL COMMENT '老新充值次数',
  `on_pay_value` decimal(11,2) NOT NULL COMMENT '老新充值金额(RMB)',
  `mon_pa` int(11) NOT NULL COMMENT '月老新充值人数(目前是哪一天就计算到哪一天)',
  `oo_pa` int(11) NOT NULL COMMENT '老老充值人数',
  `oo_pay_times` int(11) NOT NULL COMMENT '老老充值次数',
  `oo_pay_value` decimal(11,2) NOT NULL COMMENT '老老充值金额(RMB)',
  `moo_pa` int(11) NOT NULL COMMENT '月老老充值人数(目前是哪一天就计算到哪一天)',
  `pa` int(11) NOT NULL COMMENT '总充值用户',
  `dpa` int(11) NOT NULL COMMENT '日充值用户',
  `dp_times` int(11) NOT NULL COMMENT '日充值次数',
  `apa` int(11) NOT NULL COMMENT '活跃付费用户',
  `first_pay_user` int(11) NOT NULL COMMENT '日首充人数',
  `first_pay_times` int(11) NOT NULL COMMENT '日首充次数',
  `first_pay_value` decimal(11,2) NOT NULL COMMENT '日首充金额(RMB)',
  `five_minute_count` text NOT NULL COMMENT '一天中每五分钟在线人数（逗号分割共288段）',
  `second_remainer` int(11) NOT NULL COMMENT '新注册次日留存',
  `third_remainer` int(11) NOT NULL COMMENT '新注册三日留存',
  `foruth_remainer` int(11) NOT NULL COMMENT '新注册4日留存',
  `fifth_remainer` int(11) NOT NULL COMMENT '新注册第5日留存',
  `sixth_remainer` int(11) NOT NULL COMMENT '新注册第6日留存',
  `seventh_remainer` int(11) NOT NULL COMMENT '新注册7日留存',
  `doubleweek_remainer` int(11) NOT NULL COMMENT '新注册双周留存',
  `month_remainer` int(11) NOT NULL COMMENT '新注册月留存',
  `log_year` int(11) NOT NULL,
  `log_month` int(11) NOT NULL COMMENT '统计时间-月（例如：201412）',
  `log_day` int(11) NOT NULL COMMENT '统计时间-天（例如：20141208）',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=54967 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stat_job_level_distribution`;
CREATE TABLE `stat_job_level_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) DEFAULT NULL,
  `area_id` int(11) DEFAULT NULL,
  `job` varchar(64) DEFAULT NULL,
  `level` int(10) DEFAULT NULL,
  `num` int(11) DEFAULT NULL COMMENT '人数',
  `log_day` int(10) DEFAULT NULL,
  `add_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stat_job_vip_distribution`;
CREATE TABLE `stat_job_vip_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) DEFAULT NULL,
  `area_id` int(11) DEFAULT NULL,
  `job` varchar(64) DEFAULT NULL,
  `vip_level` int(10) DEFAULT NULL COMMENT '-1免费用户，0付费用户，1表示VIP1，2表示VIP2以此类推',
  `num` int(11) DEFAULT NULL COMMENT '人数',
  `log_day` int(10) DEFAULT NULL,
  `add_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stat_level_online_distribution`;
CREATE TABLE `stat_level_online_distribution` (
  `id` int(36) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL DEFAULT '0' COMMENT '0-5分钟在线人数',
  `section_2` int(11) NOT NULL DEFAULT '0' COMMENT '5-10分钟在线人数',
  `section_3` int(11) NOT NULL DEFAULT '0' COMMENT '10-15分钟在线人数',
  `section_4` int(11) NOT NULL DEFAULT '0' COMMENT '15-20分钟在线人数',
  `section_5` int(11) NOT NULL DEFAULT '0' COMMENT '20-25分钟在线人数',
  `section_6` int(11) NOT NULL DEFAULT '0' COMMENT '25-30分钟在线人数',
  `section_7` int(11) NOT NULL DEFAULT '0' COMMENT '30-60分钟在线人数',
  `section_8` int(11) NOT NULL DEFAULT '0' COMMENT '60-90分钟在线人数',
  `section_9` int(11) NOT NULL DEFAULT '0' COMMENT '90-120分钟在线人数',
  `section_10` int(11) NOT NULL DEFAULT '0' COMMENT '120-150分钟在线人数',
  `section_11` int(11) NOT NULL DEFAULT '0' COMMENT '150-180分钟在线人数',
  `section_12` int(11) NOT NULL DEFAULT '0' COMMENT '180-240分钟在线人数',
  `section_13` int(11) NOT NULL DEFAULT '0' COMMENT '240-300分钟在线人数',
  `section_14` int(11) NOT NULL DEFAULT '0' COMMENT '300-360分钟在线人数',
  `section_15` int(11) NOT NULL DEFAULT '0' COMMENT '大于360分钟在线人数',
  `log_month` int(11) NOT NULL COMMENT '日志记录时间（精确到月份）',
  `log_day` int(11) NOT NULL COMMENT '日志记录时间（精确到天）',
  `log_hour` int(11) NOT NULL COMMENT '日志记录时间（精确到小时）',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_log_day` (`log_day`)
) ENGINE=MyISAM AUTO_INCREMENT=18595 DEFAULT CHARSET=utf8 COMMENT='在线等级分布(每天一条记录)';

DROP TABLE IF EXISTS `stat_level_online_time`;
CREATE TABLE `stat_level_online_time` (
  `id` int(36) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `level` int(11) NOT NULL COMMENT '角色等级',
  `num` int(11) NOT NULL COMMENT '活跃人数(在线人数）',
  `tot` bigint(20) DEFAULT NULL COMMENT '总在线时长',
  `dt` bigint(20) DEFAULT NULL COMMENT '平均在线时长',
  `log_month` int(11) NOT NULL COMMENT '日志记录时间（精确到月份）',
  `log_day` int(11) NOT NULL COMMENT '日志记录时间（精确到天）',
  `log_hour` int(11) NOT NULL COMMENT '日志记录时间（精确到小时）',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_log_day` (`log_day`)
) ENGINE=MyISAM AUTO_INCREMENT=252453 DEFAULT CHARSET=utf8 COMMENT='在线等级分布(每天一条记录)';

DROP TABLE IF EXISTS `stat_monthly_consume`;
CREATE TABLE `stat_monthly_consume` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `is_open_month` int(11) NOT NULL,
  `income` decimal(11,2) NOT NULL,
  `pay_coin` bigint(11) NOT NULL COMMENT '充值元宝数量',
  `account` int(11) NOT NULL COMMENT '消费人数',
  `times` int(11) NOT NULL COMMENT '消费次数',
  `amount` bigint(11) NOT NULL COMMENT '消费金额(元宝)',
  `ru` int(11) NOT NULL COMMENT '注册用户',
  `au` int(11) NOT NULL COMMENT '活跃用户',
  `ou` int(11) NOT NULL COMMENT '老用户数',
  `first_consume_account` int(11) NOT NULL COMMENT '首次消费人数',
  `first_consume_amount` bigint(11) NOT NULL COMMENT '首次消费金额(元宝)',
  `log_month` int(11) NOT NULL COMMENT '例如201412',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1182 DEFAULT CHARSET=utf8 COMMENT='元宝月消费数据';

DROP TABLE IF EXISTS `stat_monthly_consume_banding`;
CREATE TABLE `stat_monthly_consume_banding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `is_open_month` int(11) NOT NULL,
  `income` decimal(11,2) NOT NULL COMMENT '收入',
  `pay_coin` bigint(11) NOT NULL COMMENT '充值元宝数量',
  `produce` bigint(11) NOT NULL COMMENT '绑定元宝产出数量',
  `total` bigint(11) NOT NULL COMMENT '绑定元宝总量（剩余）',
  `account` int(11) NOT NULL COMMENT '消费绑定元宝人数',
  `times` int(11) NOT NULL COMMENT '消费绑定元宝次数',
  `amount` bigint(11) NOT NULL COMMENT '消费绑定元宝金额',
  `ru` int(11) NOT NULL COMMENT '新注册人数',
  `au` int(11) NOT NULL COMMENT '活跃用户数',
  `ou` int(11) NOT NULL COMMENT '老用户数量',
  `first_consume_account` int(11) NOT NULL COMMENT '首次消费绑定元宝人数',
  `first_consume_amount` bigint(11) NOT NULL COMMENT '首次消费绑定元宝金额',
  `log_month` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1219 DEFAULT CHARSET=utf8 COMMENT='绑定元宝月消费数据';

DROP TABLE IF EXISTS `stat_monthly_integrated`;
CREATE TABLE `stat_monthly_integrated` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `is_open_month` int(1) NOT NULL COMMENT '是否是当月开服(0-不是，1-是)',
  `income` decimal(10,2) NOT NULL COMMENT '月收入',
  `au` int(11) NOT NULL COMMENT '月活跃',
  `ru` int(11) NOT NULL COMMENT '月注册用户数',
  `ru_gunfu` int(11) NOT NULL COMMENT '月新注册用户数中的滚服用户数',
  `acu` int(11) NOT NULL,
  `pcu` int(11) NOT NULL COMMENT '单服单月pcu',
  `dt` int(11) NOT NULL COMMENT '平均在线时长',
  `ou` int(11) NOT NULL COMMENT '月老用户数',
  `month_remainer` int(11) NOT NULL COMMENT '月留存',
  `pa` int(11) NOT NULL COMMENT '月充值用户数',
  `pay_times` int(11) NOT NULL COMMENT '月充值次数',
  `first_pay_user` int(11) NOT NULL COMMENT '月首充人数',
  `first_pay_times` int(11) NOT NULL COMMENT '月首充次数',
  `first_pay_value` decimal(10,2) NOT NULL COMMENT '月首充金额',
  `nn_pa` int(11) NOT NULL COMMENT '月新新充值人数',
  `nn_pay_times` int(11) NOT NULL COMMENT '月新新充值次数',
  `nn_pay_value` decimal(10,2) NOT NULL COMMENT '月新新充值金额',
  `ou_pa` int(11) NOT NULL COMMENT '月老充值用户数',
  `ou_pay_times` int(11) NOT NULL COMMENT '月老充值次数',
  `ou_pay_value` decimal(10,2) NOT NULL COMMENT '月老充值金额',
  `five_minute_count` text NOT NULL COMMENT '单服单月每五分钟在线人数（逗号分割共288段）',
  `log_month` int(11) NOT NULL COMMENT '统计月份',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1960 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stat_online_time_distribution`;
CREATE TABLE `stat_online_time_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL COMMENT '0-1点在线人数',
  `section_2` int(11) NOT NULL COMMENT '1-2点在线人数',
  `section_3` int(11) NOT NULL COMMENT '2-3点在线人数',
  `section_4` int(11) NOT NULL COMMENT '3-4点在线人数',
  `section_5` int(11) NOT NULL COMMENT '4-5点在线人数',
  `section_6` int(11) NOT NULL COMMENT '5-6点在线人数',
  `section_7` int(11) NOT NULL COMMENT '6-7点在线人数',
  `section_8` int(11) NOT NULL COMMENT '7-8点在线人数',
  `section_9` int(11) NOT NULL COMMENT '8-9点在线人数',
  `section_10` int(11) NOT NULL COMMENT '9-10点在线人数',
  `section_11` int(11) NOT NULL COMMENT '10-11点在线人数',
  `section_12` int(11) NOT NULL COMMENT '11-12点在线人数',
  `section_13` int(11) NOT NULL COMMENT '12-13点在线人数',
  `section_14` int(11) NOT NULL COMMENT '13-14点在线人数',
  `section_15` int(11) NOT NULL COMMENT '14-15点在线人数',
  `section_16` int(11) NOT NULL COMMENT '15-16点在线人数',
  `section_17` int(11) NOT NULL COMMENT '16-17点在线人数',
  `section_18` int(11) NOT NULL COMMENT '17-18点在线人数',
  `section_19` int(11) NOT NULL COMMENT '18-19点在线人数',
  `section_20` int(11) NOT NULL COMMENT '19-20点在线人数',
  `section_21` int(11) NOT NULL COMMENT '20-21点在线人数',
  `section_22` int(11) NOT NULL COMMENT '21-22点在线人数',
  `section_23` int(11) NOT NULL COMMENT '22-23点在线人数',
  `section_24` int(11) NOT NULL COMMENT '23-24点在线人数',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6174 DEFAULT CHARSET=utf8 COMMENT='平台在线时间段分布';

DROP TABLE IF EXISTS `stat_recharge_distribution`;
CREATE TABLE `stat_recharge_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `num` int(11) NOT NULL COMMENT '充值人数',
  `amount` decimal(10,2) NOT NULL COMMENT '充值金额',
  `section` int(11) NOT NULL COMMENT '充值金额区间(共25个区间范围,用1~25表示)',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=557576 DEFAULT CHARSET=utf8 COMMENT='充值区间分布';

DROP TABLE IF EXISTS `stat_recharge_time_distribution`;
CREATE TABLE `stat_recharge_time_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL COMMENT '0-1点充值人数',
  `section_2` int(11) NOT NULL COMMENT '1-2点充值人数',
  `section_3` int(11) NOT NULL COMMENT '2-3点充值人数',
  `section_4` int(11) NOT NULL COMMENT '3-4点充值人数',
  `section_5` int(11) NOT NULL COMMENT '4-5点充值人数',
  `section_6` int(11) NOT NULL COMMENT '5-6点充值人数',
  `section_7` int(11) NOT NULL COMMENT '6-7点充值人数',
  `section_8` int(11) NOT NULL COMMENT '7-8点充值人数',
  `section_9` int(11) NOT NULL COMMENT '8-9点充值人数',
  `section_10` int(11) NOT NULL COMMENT '9-10点充值人数',
  `section_11` int(11) NOT NULL COMMENT '10-11点充值人数',
  `section_12` int(11) NOT NULL COMMENT '11-12点充值人数',
  `section_13` int(11) NOT NULL COMMENT '12-13点充值人数',
  `section_14` int(11) NOT NULL COMMENT '13-14点充值人数',
  `section_15` int(11) NOT NULL COMMENT '14-15点充值人数',
  `section_16` int(11) NOT NULL COMMENT '15-16点充值人数',
  `section_17` int(11) NOT NULL COMMENT '16-17点充值人数',
  `section_18` int(11) NOT NULL COMMENT '17-18点充值人数',
  `section_19` int(11) NOT NULL COMMENT '18-19点充值人数',
  `section_20` int(11) NOT NULL COMMENT '19-20点充值人数',
  `section_21` int(11) NOT NULL COMMENT '20-21点充值人数',
  `section_22` int(11) NOT NULL COMMENT '21-22点充值人数',
  `section_23` int(11) NOT NULL COMMENT '22-23点充值人数',
  `section_24` int(11) NOT NULL COMMENT '23-24点充值人数',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=10594 DEFAULT CHARSET=utf8 COMMENT='平台充值时间点分布';

DROP TABLE IF EXISTS `stat_reg_convertion`;
CREATE TABLE `stat_reg_convertion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `open_time` datetime NOT NULL COMMENT '开服时间',
  `open_days` int(11) NOT NULL COMMENT '开服天数',
  `step1` int(11) NOT NULL COMMENT '已进入游戏首页',
  `step2` int(11) NOT NULL COMMENT '加载Flash主程序完成',
  `step3` int(11) NOT NULL COMMENT '加载创角配置文件完成',
  `step4` int(11) NOT NULL COMMENT '到创角界面完成',
  `step5` int(11) NOT NULL COMMENT '加载创角UI文件完成(创角页访问次数)',
  `step8` int(11) NOT NULL COMMENT '玩家已经有了记录',
  `create_role_times` int(11) NOT NULL COMMENT '创角按钮点击次数',
  `role_num` int(11) NOT NULL COMMENT '角色创建成功的数量(step6)',
  `login_times` int(11) NOT NULL COMMENT '初始场景登陆次数(step7)',
  `enter_name_times` int(11) NOT NULL COMMENT '角色输入框点击次数',
  `random_times` int(11) NOT NULL COMMENT '随即按钮点击次数',
  `log_day` int(11) NOT NULL COMMENT '统计日期天20141212',
  `log_hour` int(11) NOT NULL COMMENT '统计日期小时2014121209',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stat_reg_distribution`;
CREATE TABLE `stat_reg_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `section_1` int(11) NOT NULL COMMENT '0-1小时注册人数',
  `section_2` int(11) NOT NULL COMMENT '1-2小时注册人数',
  `section_3` int(11) NOT NULL COMMENT '2-3小时注册人数',
  `section_4` int(11) NOT NULL COMMENT '3-4小时注册人数',
  `section_5` int(11) NOT NULL COMMENT '4-5小时注册人数',
  `section_6` int(11) NOT NULL COMMENT '5-6小时注册人数',
  `section_7` int(11) NOT NULL COMMENT '6-7小时注册人数',
  `section_8` int(11) NOT NULL COMMENT '7-8小时注册人数',
  `section_9` int(11) NOT NULL COMMENT '8-9小时注册人数',
  `section_10` int(11) NOT NULL COMMENT '9-10小时注册人数',
  `section_11` int(11) NOT NULL COMMENT '10-11小时注册人数',
  `section_12` int(11) NOT NULL COMMENT '11-12小时注册人数',
  `section_13` int(11) NOT NULL COMMENT '12-13小时注册人数',
  `section_14` int(11) NOT NULL COMMENT '13-14小时注册人数',
  `section_15` int(11) NOT NULL COMMENT '14-15小时注册人数',
  `section_16` int(11) NOT NULL COMMENT '15-16小时注册人数',
  `section_17` int(11) NOT NULL COMMENT '16-17小时注册人数',
  `section_18` int(11) NOT NULL COMMENT '17-18小时注册人数',
  `section_19` int(11) NOT NULL COMMENT '18-19小时注册人数',
  `section_20` int(11) NOT NULL COMMENT '19-20小时注册人数',
  `section_21` int(11) NOT NULL COMMENT '20-21小时注册人数',
  `section_22` int(11) NOT NULL COMMENT '21-22小时注册人数',
  `section_23` int(11) NOT NULL COMMENT '22-23小时注册人数',
  `section_24` int(11) NOT NULL COMMENT '23-24小时注册人数',
  `log_day` int(11) NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平台分时注册数据';

DROP TABLE IF EXISTS `stat_task_finish`;
CREATE TABLE `stat_task_finish` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) DEFAULT NULL,
  `area_id` int(11) DEFAULT NULL,
  `task_id` varchar(64) DEFAULT NULL COMMENT ' 任务ID',
  `task_limit` int(11) DEFAULT NULL COMMENT '任务等级限制',
  `vip_level` int(11) DEFAULT NULL COMMENT '-1免费用户，0付费用户，1表示VIP1以此类推',
  `task_accept` int(11) DEFAULT NULL COMMENT '任务接受人数',
  `task_complete` int(11) DEFAULT NULL COMMENT '任务完成人数',
  `log_day` int(11) DEFAULT NULL,
  `add_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务完成度统计-每天一条记录';


DROP TABLE IF EXISTS `stat_total_integrated`;
CREATE TABLE `stat_total_integrated` (
  `log_day` varchar(36) NOT NULL,
  `total_server_count` int(11) DEFAULT NULL COMMENT '当日之前所有开服数（含当日）',
  `total_earning` decimal(18,2) DEFAULT NULL,
  `total_registration` int(11) DEFAULT NULL COMMENT '当日之前累积新进人数（含当日）',
  `total_recharge_user_count` int(11) DEFAULT NULL COMMENT '当日之前累积付费人数（含当日）',
  `add_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_day`),
  UNIQUE KEY `id` (`log_day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `stat_weekly_integrated`;
CREATE TABLE `stat_weekly_integrated` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` varchar(64) NOT NULL,
  `area_id` int(11) NOT NULL,
  `is_open_week` int(11) NOT NULL COMMENT '是否本周开服',
  `income` decimal(10,2) NOT NULL COMMENT '周收入',
  `ru` int(11) NOT NULL COMMENT '周注册人数',
  `au` int(11) NOT NULL COMMENT '周活跃',
  `ou` int(11) NOT NULL COMMENT '周老用户数',
  `pu` int(11) NOT NULL COMMENT '周充值用户数',
  `pay_times` int(11) NOT NULL COMMENT '周充值次数',
  `nn_pu` int(11) NOT NULL COMMENT '周新新充值人数',
  `nn_pay_value` decimal(10,2) NOT NULL COMMENT '周新新充值金额',
  `nn_pay_times` int(11) NOT NULL COMMENT '新新充值次数',
  `ou_pu` int(11) NOT NULL COMMENT '周老充值人数',
  `ou_pay_value` decimal(10,2) NOT NULL COMMENT '周老充值金额',
  `ou_pay_times` int(11) NOT NULL COMMENT '周老充值次数',
  `log_year` int(11) NOT NULL,
  `log_week` int(11) NOT NULL COMMENT '统计日所在周,例如：201452表示2014年52周，2014年12月29-31号算为2015年第一周',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3175 DEFAULT CHARSET=utf8 COMMENT='每周一条记录，周初记录上周数据';
